# Generated by Django 5.0 on 2023-12-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like',
        ),
    ]
